<<<<<<< HEAD
# Generated by Django 2.1.2 on 2019-04-25 23:36
=======
# Generated by Django 2.1.2 on 2019-03-20 03:10
>>>>>>> f699d5591f57f717ab26728fdeb4fe59bbcf4f88

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
>>>>>>> f699d5591f57f717ab26728fdeb4fe59bbcf4f88
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
<<<<<<< HEAD
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('weight', models.IntegerField()),
                ('status', models.BooleanField()),
=======
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationOnService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'free'), ('2', 'attending'), ('3', 'paused')], max_length=1)),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Location')),
>>>>>>> f699d5591f57f717ab26728fdeb4fe59bbcf4f88
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=mainapp.models.path_profile_image)),
                ('rol', models.CharField(choices=[('a', 'administrador'), ('b', 'cajero_g'), ('c', 'cajero_ie'), ('d', 'cajero_s'), ('e', 'cajero_d'), ('f', 'cajero_vip'), ('g', 'cliente')], max_length=1)),
                ('id_card', models.CharField(blank=True, max_length=20, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
<<<<<<< HEAD
=======
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
>>>>>>> f699d5591f57f717ab26728fdeb4fe59bbcf4f88
            ],
            options={
                'permissions': (('es_cliente', 'Cliente'), ('es_proveedor', 'Proveedor'), ('es_gerente', 'Gerente'), ('es_administrador', 'Administrador'), ('es_cajero_general', 'Cajero General'), ('es_cajero_ie', 'Cajero de Importaciones y Exportaciones'), ('es_cajero_s', 'Cajero de Seguros'), ('es_cajero_d', 'Cajero de transacciones en Dólares'), ('es_cajero_vip', 'Cajero VIP')),
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ManyToManyField(blank=True, to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('service', models.CharField(max_length=512)),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
=======
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread_first', to=settings.AUTH_USER_MODEL)),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread_second', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('1', 'waiting'), ('2', 'onservice'), ('3', 'attended'), ('4', 'canceled')], max_length=1)),
                ('start_attend', models.DateTimeField(null=True)),
                ('end_attend', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Service')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Specialty')),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_client', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_employee', to=settings.AUTH_USER_MODEL)),
                ('window', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Location')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_r', to='mainapp.Specialty'),
        ),
>>>>>>> f699d5591f57f717ab26728fdeb4fe59bbcf4f88
        migrations.AddField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Thread'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
    ]
